name:                cmake-talk-site
version:             0.1.0.0
github:              "hannes-steffenhagen-diffblue/cmake-talk-site"
license:             BSD3
author:              "Hannes Steffenhagen"
maintainer:          "Hannes.Steffenhagen@diffblue.com"
copyright:           "2019 Hannes Steffenhagen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hannes-steffenhagen-diffblue/cmake-talk-site#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings

executables:
  site:
    main:                Main.hs
    source-dirs:         site
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hakyll
    - filepath
  watch:
    main: Main.hs
    source-dirs: watch
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hinotify
    - bytestring
    - process
